// ------------------------------------------------------------------------------------------------
// ï¿½ï¿½ï¿½ï¿½ï¿½: ï¿½ï¿½Ã‰lï¿½ï¿½
// ï¿½ï¿½ï¿½ï¿½ï¿½: 2025/06/07
// ï¿½dï¿½lï¿½@: ï¿½ï¿½ï¿½Í‚ï¿½ï¿½eï¿½fï¿½oï¿½Cï¿½Xï¿½ï¿½ï¿½ï¿½ó‚¯ï¿½ï¿½Aï¿½Kï¿½Ø‚È”ï¿½ï¿½ï¿½ï¿½ï¿½sï¿½ï¿½
// ------------------------------------------------------------------------------------------------

using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI;

public class Input_Player : MonoBehaviour
{
	// ï¿½Ïï¿½

	// ï¿½Vï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½gï¿½ï¿½	-------------------------------------------------------------------------------
	private InputSystemAction _input;
	public static Input_Player Instance;

	// ï¿½ï¿½ï¿½ÍŠJï¿½nï¿½ï¿½ï¿½ï¿½ï¿½uï¿½ï¿½	---------------------------------------------------------------------------
	// ï¿½Eï¿½Ú“ï¿½
	private bool _rightMove_started;
	public bool RightMove_Started => _rightMove_started;
	// ï¿½ï¿½ï¿½Ú“ï¿½
	private bool _leftMove_started;
	public bool LeftMove_Started => _leftMove_started;
	// ï¿½Eï¿½_ï¿½bï¿½Vï¿½ï¿½
	private bool _rightDash_started;
	public bool RightDash_Started => _rightDash_started;

	// ï¿½ï¿½ï¿½Í‚ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½ï¿½	-------------------------------------------------------------------------------
	// ï¿½Eï¿½Ú“ï¿½
	private bool _rightMove_performed;
	public bool RightMove_performed => _rightMove_performed;
	// ï¿½ï¿½ï¿½Ú“ï¿½
	private bool _leftMove_performed;
	public bool LeftMove_Performed => _leftMove_performed;
	// ï¿½Eï¿½_ï¿½bï¿½Vï¿½ï¿½
	private bool _rightDash_performed;
	public bool RightDash_Performed => _rightDash_performed;

	// ï¿½ï¿½ï¿½Í‰ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½uï¿½ï¿½	---------------------------------------------------------------------------
	// ï¿½Eï¿½Ú“ï¿½
	private bool _rightMove_canceled;
	public bool rightMove_Canceled => _rightMove_canceled;
	// ï¿½ï¿½ï¿½Ú“ï¿½
	private bool _leftMove_canceled;
	public bool LeftMove_Canceled => _leftMove_canceled;
	// ï¿½Eï¿½_ï¿½bï¿½Vï¿½ï¿½
	private bool _rightDash_canceled;
	public bool RightDash_Canceled => _rightDash_canceled;

	// ï¿½Cï¿½xï¿½ï¿½ï¿½gï¿½nï¿½ï¿½ï¿½hï¿½ï¿½	---------------------------------------------------------------------------
	// ï¿½Eï¿½Ú“ï¿½
	private void OnRightMove_started(InputAction.CallbackContext ctx) => _rightMove_started = true;
	private void OnRightMove_canceled(InputAction.CallbackContext ctx) => _rightMove_canceled = true;
	// ï¿½ï¿½ï¿½Ú“ï¿½
	private void OnLeftMove_started(InputAction.CallbackContext ctx) => _leftMove_started = true;
	private void OnLeftMove_canceled(InputAction.CallbackContext ctx) => _leftMove_canceled = true;
	// ï¿½Eï¿½_ï¿½bï¿½Vï¿½ï¿½
	private void OnRightDash_started(InputAction.CallbackContext ctx) => _rightDash_started = true;
	private void OnRightDash_canceled(InputAction.CallbackContext ctx) => _rightDash_canceled = true;

	// 1ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½	-------------------------------------------------------------------------------
	// ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[ï¿½Ì~ï¿½{ï¿½^ï¿½ï¿½
	private bool _gamepadSouthButton = false;

	// 2,3ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½	-------------------------------------------------------------------------------
	// ï¿½Rï¿½ï¿½ï¿½gï¿½ï¿½ï¿½[ï¿½ï¿½ï¿½[ï¿½Ìï¿½ï¿½Xï¿½eï¿½Bï¿½bï¿½N
	private Vector2 _gamepadLeftStick = Vector2.zero;
	// Joy-conï¿½Ìï¿½ï¿½ï¿½ï¿½ï¿½ï¿½x
	private Vector3 _joyconLeftAccel = Vector3.zero;

	// ï¿½ï¿½ï¿½ï¿½Ïï¿½	-----------------------------------------------------------------------------------
	// ï¿½Eï¿½Ú“ï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½ï¿½fï¿½oï¿½Cï¿½X
	bool _rightMove_vec2 = false;
	bool _rightMove_vec3 = false;
	bool _rightMove_button = false;
	// ï¿½Eï¿½Ú“ï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½ï¿½fï¿½oï¿½Cï¿½X
	bool _leftMove_vec2 = false;
	bool _leftMove_button = false;
	// ï¿½Eï¿½Ú“ï¿½ï¿½ï¿½ï¿½Ì‘ï¿½ï¿½ï¿½fï¿½oï¿½Cï¿½X
	bool _rightDash_vec2 = false;
	bool _rightDash_vec3 = false;
	bool _rightDash_button = false;
	// ï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½Ìcï¿½èï¿½ï¿½
	private float _accelTime = 0.0f;

	// ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚É•Kï¿½vï¿½ÈƒXï¿½eï¿½Bï¿½bï¿½Nï¿½ÌŒXï¿½ï¿½
	private const float _RIGHTMOVE_STICKVALUE = 0.0f;
	// ï¿½Ú“ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚É•Kï¿½vï¿½È‰ï¿½ï¿½ï¿½ï¿½x
	private const float _RIGHTMOVE_ACCELVALUE = 0.33f;
	// ï¿½_ï¿½bï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Ì‚É•Kï¿½vï¿½È‰ï¿½ï¿½ï¿½ï¿½x
	private const float _RIGHTDASH_ACCELVALUE = 2.5f;
	// ï¿½ï¿½ï¿½ï¿½pï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
	private const float _RIGHTMOVE_ACCELTIME = 0.08f;

	// Joy-Con	-----------------------------------------------------------------------------------
	// Joy-Conï¿½ï¿½ï¿½Xï¿½gï¿½iï¿½ï¿½ï¿½ï¿½ï¿½Ú‘ï¿½ï¿½ï¿½ï¿½ê‚½Joy-Conï¿½Ìï¿½ï¿½j
	private List<Joycon> _joycons;
	// Joy-Conï¿½ï¿½
	private Joycon _joyconL;



	// ï¿½Öï¿½

	/// <summary>
	/// ï¿½{ï¿½^ï¿½ï¿½ï¿½ï¿½ï¿½Í‚É‚ï¿½é‘€ï¿½ï¿½ï¿½ï¿½ó‚¯•tï¿½ï¿½ï¿½ï¿½
	/// </summary>
	public void Action_Button()
	{
		// ï¿½Eï¿½Ú“ï¿½	-------------------------------------------------------------------------------
		// ï¿½ï¿½ï¿½ÍŠJï¿½n
		if (_rightMove_started)
		{
			_rightMove_started = false;
			_rightMove_button = true;
		}
		// ï¿½ï¿½ï¿½Í‰ï¿½ï¿½ï¿½
		else if (_rightMove_canceled)
		{
			_rightMove_canceled = false;
			_rightMove_button = false;
		}

		// ï¿½ï¿½ï¿½Ú“ï¿½	-------------------------------------------------------------------------------
		// ï¿½ï¿½ï¿½ÍŠJï¿½n
		if (_leftMove_started)
		{
			_leftMove_started = false;
			_leftMove_button = true;
		}
		// ï¿½ï¿½ï¿½Í‰ï¿½ï¿½ï¿½
		if (_leftMove_canceled)
		{
			_leftMove_canceled = false;
			_leftMove_button = false;
		}

		// ï¿½Eï¿½_ï¿½bï¿½Vï¿½ï¿½	---------------------------------------------------------------------------
		// ï¿½ï¿½ï¿½ÍŠJï¿½n
		if (_rightDash_started)
		{
			_rightDash_started = false;
			_rightDash_button = true;
		}
		// ï¿½ï¿½ï¿½Í‰ï¿½ï¿½ï¿½
		else if (_rightDash_canceled)
		{
			_rightDash_canceled = false;
			_rightDash_button = false;
		}
	}

	/// <summary>
	/// 2ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½(ï¿½Xï¿½eï¿½Bï¿½bï¿½Nï¿½ï¿½)ï¿½É‚ï¿½é‘€ï¿½ï¿½ï¿½ï¿½ó‚¯•tï¿½ï¿½ï¿½ï¿½
	/// </summary>
	private void Action_Vec2()
	{
		// ï¿½Eï¿½Ú“ï¿½	-------------------------------------------------------------------------------
		// ï¿½ï¿½ï¿½lï¿½Ü‚ÅƒXï¿½eï¿½Bï¿½bï¿½Nï¿½ï¿½ï¿½Xï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
		if (_gamepadLeftStick.x > _RIGHTMOVE_STICKVALUE && !_gamepadSouthButton)
		{
			_rightMove_vec2 = true;
		}
		else
		{
			_rightMove_vec2 = false;
		}

		// ï¿½ï¿½ï¿½Ú“ï¿½	-------------------------------------------------------------------------------
		// ï¿½ï¿½ï¿½lï¿½Ü‚ÅƒXï¿½eï¿½Bï¿½bï¿½Nï¿½ï¿½ï¿½Xï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
		if (_gamepadLeftStick.x < -_RIGHTMOVE_STICKVALUE)
		{
			_leftMove_vec2 = true;
		}
		else
		{
			_leftMove_vec2 = false;
		}

		// ï¿½Eï¿½_ï¿½bï¿½Vï¿½ï¿½	---------------------------------------------------------------------------
		// ï¿½ï¿½ï¿½lï¿½Ü‚ÅƒXï¿½eï¿½Bï¿½bï¿½Nï¿½ï¿½ï¿½Xï¿½ï¿½ï¿½Ä‚ï¿½ï¿½ï¿½
		if (_gamepadLeftStick.x > _RIGHTMOVE_STICKVALUE && _gamepadSouthButton)
		{
			_rightDash_vec2 = true;
		}
		else
		{
			_rightDash_vec2 = false;
		}
	}

	/// <summary>
	/// 2ï¿½ï¿½ï¿½ï¿½ï¿½Iï¿½ï¿½ï¿½ï¿½(Joyconï¿½ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½)ï¿½É‚ï¿½é‘€ï¿½ï¿½ï¿½ï¿½ó‚¯•tï¿½ï¿½ï¿½ï¿½
	/// </summary>
	private void Action_Vec3()
	{
		// Joy-conLï¿½Ì‰ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½Î’lï¿½ï¿½
		Vector3 joyconAccel = AbsoluteVec3(_joyconLeftAccel);

		// ï¿½Eï¿½Ú“ï¿½	-------------------------------------------------------------------------------
		// ï¿½ï¿½ï¿½ï¿½ï¿½ê‚©ï¿½Ìï¿½ï¿½Ì‰ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½Èã‚©ï¿½ÂAï¿½Eï¿½_ï¿½bï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Å‚È‚ï¿½ï¿½ê‡
		if ((((joyconAccel.x > _RIGHTMOVE_ACCELVALUE && joyconAccel.x < _RIGHTDASH_ACCELVALUE) ||
			  (joyconAccel.y > _RIGHTMOVE_ACCELVALUE && joyconAccel.y < _RIGHTDASH_ACCELVALUE) ||
			  (joyconAccel.z > _RIGHTMOVE_ACCELVALUE && joyconAccel.z < _RIGHTDASH_ACCELVALUE)) && !_rightDash_vec3))
		{
			_rightMove_vec3 = true;
			_rightDash_vec3 = false;
			_accelTime = _RIGHTMOVE_ACCELTIME;
		}

		// ï¿½Eï¿½_ï¿½bï¿½Vï¿½ï¿½	---------------------------------------------------------------------------
		// ï¿½ï¿½ï¿½ï¿½ï¿½ê‚©ï¿½Ìï¿½ï¿½Ì‰ï¿½ï¿½ï¿½ï¿½xï¿½ï¿½ï¿½ï¿½ï¿½Èï¿½Ìê‡
		else if (joyconAccel.x >= _RIGHTDASH_ACCELVALUE ||
				 joyconAccel.y >= _RIGHTDASH_ACCELVALUE ||
				 joyconAccel.z >= _RIGHTDASH_ACCELVALUE)
		{
			_rightDash_vec3 = true;
			_rightMove_vec3 = false;
			_accelTime = _RIGHTMOVE_ACCELTIME;
		}

		// ï¿½ï¿½ï¿½ï¿½ï¿½xï¿½Ìƒï¿½ï¿½ï¿½ï¿½É‚ï¿½ï¿½eï¿½ï¿½ï¿½ï¿½ï¿½yï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
		if (_accelTime > 0)
		{
			_accelTime -= Time.deltaTime;
		}
		else
		{
			_accelTime = 0;
			_rightMove_vec3 = false;
			_rightDash_vec3 = false;
		}
	}

	/// <summary>
	/// ï¿½Aï¿½Nï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ï¿½Lï¿½ï¿½ï¿½É‚ï¿½ï¿½ï¿½
	/// </summary>
	private void Action()
	{
		// ï¿½Eï¿½Ú“ï¿½
		_rightMove_performed = _rightMove_button || _rightMove_vec2 || _rightMove_vec3;
		// ï¿½ï¿½ï¿½Ú“ï¿½
		_leftMove_performed = _leftMove_button || _leftMove_vec2;
		// ï¿½Eï¿½_ï¿½bï¿½Vï¿½ï¿½
		_rightDash_performed = _rightDash_button || _rightDash_vec2 || _rightDash_vec3;
	}

	/// <summary>
	/// ï¿½Oï¿½ï¿½ï¿½fï¿½oï¿½Cï¿½Xï¿½Ì“ï¿½ï¿½Íï¿½ï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½
	/// </summary>
	private void GetInput()
	{
		// ï¿½Qï¿½[ï¿½ï¿½ï¿½pï¿½bï¿½hLï¿½Xï¿½eï¿½Bï¿½bï¿½N
		if (Gamepad.all.Count > 0) _gamepadLeftStick = Gamepad.current.leftStick.ReadValue();
		// ï¿½Qï¿½[ï¿½ï¿½ï¿½pï¿½bï¿½hï¿½~ï¿½{ï¿½^ï¿½ï¿½
		if (Gamepad.all.Count > 0) _gamepadSouthButton = Gamepad.current.buttonSouth.isPressed;

		// Joy-conLï¿½ï¿½ï¿½ï¿½ï¿½x
		if (_joycons.Count > 0) _joyconLeftAccel = _joyconL.GetAccel();

		// Joy-conï¿½Ì‰ï¿½ï¿½ï¿½ï¿½xï¿½ğ³ï¿½É–ß‚ï¿½ï¿½ï¿½ï¿½ß‚ÌƒIï¿½tï¿½Zï¿½bï¿½g
		Vector3 ofset = Vector3.zero;
		// xï¿½ï¿½
		if (_joyconLeftAccel.x > 1.0f) ofset.x = 1.0f;
		else if (_joyconLeftAccel.x < -1.0f) ofset.x = -1.0f;
		else ofset.x = _joyconLeftAccel.x;
		// yï¿½ï¿½
		if (_joyconLeftAccel.y > 1.0f) ofset.y = 1.0f;
		else if (_joyconLeftAccel.y < -1.0f) ofset.y = -1.0f;
		else ofset.y = _joyconLeftAccel.y;
		// zï¿½ï¿½
		if (_joyconLeftAccel.z > 1.0f) ofset.z = 1.0f;
		else if (_joyconLeftAccel.z < -1.0f) ofset.z = -1.0f;
		else ofset.z = _joyconLeftAccel.z;
		// ï¿½ï¿½ï¿½ï¿½
		_joyconLeftAccel -= ofset;
	}

	/// <summary>
	/// ï¿½Ú‘ï¿½ï¿½ï¿½ï¿½ê‚½JoyConï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½
	/// </summary>
	private void FindJoycon()
	{
		// Joy-Conï¿½Ìƒï¿½ï¿½Xï¿½gï¿½ï¿½ï¿½æ“¾
		_joycons = JoyconManager.Instance.j;

		// Joyconï¿½ï¿½Ú‘ï¿½ï¿½ï¿½ï¿½ï¿½
		if (_joycons.Count > 0)
		{
			_joyconL = _joycons[0];
			Debug.Log("Joy-Conï¿½ï¿½ï¿½Ú‘ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½ï¿½B");

		}
		else
		{
			Debug.LogWarning("Joy-Conï¿½ï¿½ï¿½Ú‘ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½B");
		}

		// Debug: ï¿½Qï¿½[ï¿½ï¿½ï¿½pï¿½bï¿½hï¿½ÌÚ‘ï¿½ï¿½ï¿½ï¿½mï¿½Fï¿½ï¿½ï¿½ï¿½
		if (Gamepad.all.Count > 0)
		{
			Debug.Log("ï¿½Qï¿½[ï¿½ï¿½ï¿½pï¿½bï¿½hï¿½ï¿½ï¿½Ú‘ï¿½ï¿½ï¿½ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½ï¿½B");
		}
		else
		{
			Debug.LogWarning("ï¿½Qï¿½[ï¿½ï¿½ï¿½pï¿½bï¿½hï¿½ï¿½ï¿½Ú‘ï¿½ï¿½ï¿½ï¿½ï¿½Ä‚ï¿½ï¿½Ü‚ï¿½ï¿½ï¿½B");
		}
	}

	/// <summary>
	/// ï¿½wï¿½è‚µï¿½ï¿½Vector3ï¿½^ï¿½Ì•Ïï¿½ï¿½Ìï¿½Î’lï¿½ï¿½ï¿½oï¿½Í‚ï¿½ï¿½ï¿½
	/// </summary>
	/// <returns></returns>
	private Vector3 AbsoluteVec3(Vector3 vec3)
	{
		return new Vector3(
			Mathf.Abs(vec3.x),
			Mathf.Abs(vec3.y),
			Mathf.Abs(vec3.z)
			);
	}

	/// <summary>
	/// ï¿½fï¿½oï¿½bï¿½O
	/// </summary>
	public void PrintText_GamepadLstick(Text text)
	{
		if (Gamepad.all.Count <= 0)
		{
			text.text = "Could not access gamepad";
			return;
		}
		text.text = $"x: {_gamepadLeftStick.x}  y: {_gamepadLeftStick.y}";
	}

	/// <summary>
	/// ï¿½fï¿½oï¿½bï¿½O
	/// </summary>
	public void PrintText_JoyconLaccel(Text text)
	{
		if (_joycons.Count <= 0)
		{
			text.text = "Could not access Joy-con";
			return;
		}
		text.text = $"x: {_joyconLeftAccel.x}\ny: {_joyconLeftAccel.y}\nz: {_joyconLeftAccel.z}";
	}



	// Unity Events

	private void Awake()
	{
		_input = new InputSystemAction();

		// ï¿½Vï¿½ï¿½ï¿½Oï¿½ï¿½ï¿½gï¿½ï¿½ï¿½Ìì¬
		if (Instance == null)
		{
			Instance = this;
		}
		else
		{
			Destroy(this);
		}
	}
	private void Start()
	{
		FindJoycon();
	}

	private void Update()
	{
		GetInput();
		Action_Button();
		Action_Vec2();
		Action_Vec3();
		Action();
	}

	private void OnEnable()
	{
		_input.Enable();

		// ï¿½Eï¿½Ú“ï¿½
		_input.Player.RightMove.started += OnRightMove_started;
		_input.Player.RightMove.canceled += OnRightMove_canceled;

		// ï¿½ï¿½ï¿½Ú“ï¿½
		_input.Player.LeftMove.started += OnLeftMove_started;
		_input.Player.LeftMove.canceled += OnLeftMove_canceled;

		// ï¿½Eï¿½_ï¿½bï¿½Vï¿½ï¿½
		_input.Player.RightDash.started += OnRightDash_started;
		_input.Player.RightDash.canceled += OnRightDash_canceled;
	}


	private void OnDisable()
	{
		_input.Disable();

		// ï¿½Eï¿½Ú“ï¿½
		_input.Player.RightMove.started -= OnRightMove_started;
		_input.Player.RightMove.canceled -= OnRightMove_canceled;

		// ï¿½ï¿½ï¿½Ú“ï¿½
		_input.Player.LeftMove.started -= OnLeftMove_started;
		_input.Player.LeftMove.canceled -= OnLeftMove_canceled;

		// ï¿½Eï¿½_ï¿½bï¿½Vï¿½ï¿½
		_input.Player.RightDash.started -= OnRightDash_started;
		_input.Player.RightDash.canceled -= OnRightDash_canceled;
	}

	public void OnBuruBuru()
	{
		_joyconL.SetRumble(320, 640, 1.0f, 300);
    }

	public void Restart()
	{
		FindJoycon();
	}

}